ALTER TABLE `REL_ALBUMS_ORIGINALES` ADD `id_album` INT  NULL  DEFAULT NULL  AFTER `id`;
ALTER TABLE `REL_ALBUMS_ORIGINALES` ADD `id_user` INT  NULL  DEFAULT NULL  AFTER `id_album`;
ALTER TABLE `REL_ALBUMS_ORIGINALES` CHANGE `id_album` `id_album` INT(11)  NOT NULL;
ALTER TABLE `REL_ALBUMS_ORIGINALES` CHANGE `id_user` `id_user` INT(11)  NOT NULL;
CREATE TABLE `DBVERSION` (id INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT) DEFAULT CHARACTER SET `utf8`;
ALTER TABLE `DBVERSION` ADD `version` INT  NOT NULL  AFTER `id`;
ALTER TABLE `DBVERSION` ADD `fecha` DATETIME  NOT NULL  AFTER `version`;
INSERT INTO `DBVERSION` (`id`, `version`, `fecha`) VALUES ('', '1', '2012-05-28 13:50:00');